# [아이템 75] 예외의 상세 메시지에 실패 관련 정보를 담으라

## Stack Trace

```java
java.lang.Exception: java.lang.RuntimeException: java.lang.NullPointerException
	at com.test.TestMain.main(TestMain.java:27)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.test.TestMain.main(TestMain.java:21)
	Suppressed: java.lang.Exception: test runtime suppressed exception6
		at com.test.TestMain.main(TestMain.java:26)
Caused by: java.lang.NullPointerException
	at com.test.TestMain.main(TestMain.java:16)
	Suppressed: java.lang.Exception: test suppressed exception1
		at com.test.TestMain.main(TestMain.java:18)
	Suppressed: java.lang.Exception: test suppressed exception2
		at com.test.TestMain.main(TestMain.java:19)
	Suppressed: java.lang.Exception: test suppressed exception3
		at com.test.TestMain.main(TestMain.java:20)
```

하나의 프로그램을 수행하는 동안 스레드는 여러 메서드를 돌아다닙니다. 메서드가 호출되고 종료되면, 메서드를 호출한 곳으로 다시 돌아가야 하는데 이를 위해 Stack에 메서드가 호출된 포인트를 기록해놓게 됩니다.

즉 프로그램 실행 중 기록되는 특정 포인트를 쌓아놓고 활용하는 것이 stack trace인거죠.

```java
public void printStackTrace() {
        printStackTrace(System.err);
    }

    /**
     * Prints this throwable and its backtrace to the specified print stream.
     *
     * @param s {@code PrintStream} to use for output
     */
    public void printStackTrace(PrintStream s) {
        printStackTrace(new WrappedPrintStream(s));
    }

    private void printStackTrace(PrintStreamOrWriter s) {
        // Guard against malicious overrides of Throwable.equals by
        // using a Set with identity equality semantics.
        Set<Throwable> dejaVu =
            Collections.newSetFromMap(new IdentityHashMap<Throwable, Boolean>());
        dejaVu.add(this);

        synchronized (s.lock()) {
            // Print our stack trace
            s.println(this);
            StackTraceElement[] trace = getOurStackTrace();
            for (StackTraceElement traceElement : trace)
                s.println("\tat " + traceElement);

            // Print suppressed exceptions, if any
            for (Throwable se : getSuppressed())
                se.printEnclosedStackTrace(s, trace, SUPPRESSED_CAPTION, "\t", dejaVu);

            // Print cause, if any
            Throwable ourCause = getCause();
            if (ourCause != null)
                ourCause.printEnclosedStackTrace(s, trace, CAUSE_CAPTION, "", dejaVu);
        }
    }
```

Throwable 클래스를 뜯어보면 printStackTrace 메서드를 찾을 수 있습니다.

PrintStreamIrWriter s 변수 사용하는 것을 보면 아래 순서로 출력됩니다.

```java
1. s.println(this)
2. getOurStackTrace() 를 loop돌면서 s.println(“\tat “ + traceElement);
3. getSuppressed()를 loop돌면서 se.printEnclosedStackTrace(s, trace, SUPPRESSED_CAPTION, “\t”, dejaVu);
4. getCause() 가 null이 아니라면 ourCause.printEnclosedStackTrace(s, trace, CAUSE_CAPTION, “”, dejaVu);
```

1. println(this)는 각 Exception class가 toString을 override하지 않는다면 Throwable의 toString메소드에 따라 아래와 같은 로직으로 출력됩니다.

```java
public String toString() {
        String s = getClass().getName();
        String message = getLocalizedMessage();
        return (message != null) ? (s + ": " + message) : s;
}
```

printStacTrace 최상단의 [Exception클래스명 : 메시지]가 출력되는 것이죠.

2. getOurStackTrace()는 StackTraceElement배열을 리턴합니다.

loop를 돌면서 [탭문자 + “at” + StackTraceElement.toString()] 를 출력합니다.

StackTraceElement가 담는것은 제일 바깥으로 나오는 Exception의 stack들입니다.

3. getSuppressed() 에서 suppressed Exception(java7추가)들을 가져와 출력하고

4. getCause() 에서는 chaing된 Throwable을 리턴하여 위와 같은 출력 로직을 실행해줍니다.

이러한 stack trace들은 예외 디버깅에서 굉장히 중요합니다.

> 실패 순간을 포착하려면 발생한 예외에 관여된 모든 매개변수와 필드의 값을 실패 메시지에 담아야 한다.

더 정확한 디버깅을 위해서 예외 메시지에 실패와 관련된 정보를 더 많이 담으라는 거겠죠.

## Custom Exception

사이드 프로젝트에서 커스텀 예외를 구현해보며 참고했던 4가지의 Best Practice가 있습니다. 이번 아이템과 관련하여 공유하면 좋을 것 같아 가져왔어요.

### 1. Always Provide a Benefit

커스텀 예외의 의도는 “자바의 표준 예외로 표현할 수 없는 정보 제공”에 있습니다. 그러므로 이 의도를 항상 상기하며 장점(Benefit)을 뽑아내야 합니다.

만약 특출난 장점이 없는 예외라면 UnsupportedOperationException 이나 IllegalArgumentException 과 같이 표준 예외들 중 하나를 사용하는게 낫습니다. 표준 예외가 개발자들 사이에서 더 이해하기 쉽기 때문이죠.

### 2. Follow the Naming Convention

자바 라이브러리 예외 네이밍 컨벤션을 따르는 것은 규칙입니다. 모두가 이해하기 쉽게 작성하기.

### 3. Provide Javadoc Comments for Your Exception Class

이전 아이템에서 언급했듯 문서화는 중요하고, 예외 클래스에 대해서도 적절하게 문서화해주는 것이 좋습니다.

(\* Exception을 던지는 메서드나 클래스 레벨에서도 문서화가 중요하다고 이미 언급했으니 넘어가겠습니다.)

예외는 곧 API의 일부가 되기 때문에 어떤 상황에서 예외가 발생하는지를 기술해놓는 것이 필수적입니다.

### 4. Provider Constructor That Sets the Cause

보통 커스텀 예외를 사용하면 표준 예외를 catch해서 커스텀 예외로 던지는 경우가 많습니다.

![](https://velog.velcdn.com/images/jmjmjmz732002/post/bc2fc118-70df-4194-886f-b5a3d0463a03/image.png)

catch된 정보를 던질 때, 이번 아이템의 핵심 내용이 나옵니다.

“필수적인 정보”를 cause로 설정하여 디버깅에 유용하게 할 것.

Exception 과 RuntimeException 은 예외의 원인을 기술하고 있는 Throwable을 받을 수 있는 생성자 메서드를 제공합니다.

커스텀 예외도 마찬가지로 cause를 바로 분석할 수 있도록 생성자에서 인자로 받아주어 super 생성자에 Throwable를 전달해주면 좋습니다.

```java
/*
* 이것은 커스텀 CheckedException 입니다.
* 자바의 기본 예외로 표현할 수 없는 예외를 제공하기 위해 만들어졌습니다.
* */
public class CustomCheckedExceptionEx extends Exception {

    public CustomCheckedExceptionEx() {
    }

    public CustomCheckedExceptionEx(String message) {
        super(message);
    }

    public CustomCheckedExceptionEx(String message, Throwable cause) {
        super(message, cause);
    }

    public CustomCheckedExceptionEx(Throwable cause) {
        super(cause);
    }

    public CustomCheckedExceptionEx(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }
}

class CustomCheckedExceptionTest {
    public static void main(String[] args) throws CustomCheckedExceptionEx {
        try {
            // doSomething
        } catch (Exception e) {
            throw new CustomCheckedExceptionEx("커스텀 체크드 예외 발생!!", e);
        }
    }
}
```

🤔 제가 개발할 때에는 편하게, 바로바로 가져다 쓰기 위해서 하나의 공통 Exception 클래스를 만들어 놓고, ErrorCode 네이밍의 Enum으로 각 예외를 구분해주었습니다. cause 관련한 메시지, rest api에서 쓰이는 상태 코드 등에 대한 관리도 Enum에서 이루어졌고요.

이게 일반적인지는 잘 모르겠습니다. 여러분들은 어떻게 구현하시는지 궁금하네요!
